name: 'Docker GHCR Action'
description: 'Build and push Docker images to GitHub Container Registry'
inputs:
  registry:
    description: 'Docker registry to use'
    required: false
    default: 'ghcr.io'
  username:
    description: 'Username for the Docker registry'
    required: true
  password:
    description: 'Password or token for the Docker registry'
    required: true
  image_name:
    description: 'Name of the Docker image'
    required: true
  dockerfile:
    description: 'Path to the Dockerfile'
    required: false
    default: 'Dockerfile'
runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Docker buildx
      uses: docker/setup-buildx-action@v3

    - name: Log into registry
      uses: docker/login-action@v2
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}

    - name: Extract Docker metadata
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ${{ inputs.registry }}/${{ inputs.image_name }}
        tags: latest

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ${{ inputs.dockerfile }}
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Delete Package Versions
      uses: actions/delete-package-versions@v4.1.0
      with:
        package-name: ${{ inputs.image_name }}
        package-type: 'container'
        min-versions-to-keep: 3
        delete-only-untagged-versions: 'true'
        token: ${{ inputs.password }}
